// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjoHlbX-i04faTF6N6pYpq1PorBq28Wto',
    appId: '1:891850945568:web:68f27df5d91a079e477845',
    messagingSenderId: '891850945568',
    projectId: 'miniproject-3fee6',
    authDomain: 'miniproject-3fee6.firebaseapp.com',
    storageBucket: 'miniproject-3fee6.appspot.com',
    measurementId: 'G-HV6FFG7QQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMNjY7bFuoCbjna85zRVcDePijaCKXDw',
    appId: '1:891850945568:android:bb5820cb8ac92221477845',
    messagingSenderId: '891850945568',
    projectId: 'miniproject-3fee6',
    storageBucket: 'miniproject-3fee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJcqsf8HXAWS7-rb9usoFbqBOuSuDQ88',
    appId: '1:891850945568:ios:6b592a99f1e0ef38477845',
    messagingSenderId: '891850945568',
    projectId: 'miniproject-3fee6',
    storageBucket: 'miniproject-3fee6.appspot.com',
    iosClientId: '891850945568-nuit31k7c01m2jfsou9uav16kc428fgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJcqsf8HXAWS7-rb9usoFbqBOuSuDQ88',
    appId: '1:891850945568:ios:6b592a99f1e0ef38477845',
    messagingSenderId: '891850945568',
    projectId: 'miniproject-3fee6',
    storageBucket: 'miniproject-3fee6.appspot.com',
    iosClientId: '891850945568-nuit31k7c01m2jfsou9uav16kc428fgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
